baseURL = 'https://dastaminophen.com/'
languageCode = 'fa-ir'
title = 'داستامینوفن'
theme = "DastaminophenBloggeTheme"

paginate = 6
summarylength = 10

[menu]
  [[menu.main]]
    name = "Home"
    url= ""
    weight= 1
  [[menu.main]]
    name = "About"
    url= "about"
    weight= 2
  [[menu.main]]
    name = "Contact"
    url= "contact"
    weight= 3

[params]
  summarylength = 80
  logo = "images/logo.svg"
  author = "ایمان نجیمی"
  authorThumb = "images/author.png"
  instaUsername = "dastaminophen"
  telegramUsername = "dastaminophen"
  twitterUsername = "dastaminophen"
  linkedinUsername = "dastaminophen"
  blogTitle = "داستامینوفن"
  blogSubTitle = "پادکستی برای دوستداران قصّه"
  trendingBlogIcon = "images/blog/icon.svg"
  # Replace the third party URL/API with yours
  # We're using formspree.io for form handling, paste your formspree url below
  fabformURL  = "9AJk8ro"

[taxonomies]
  tag = "tags"
