
baseURL: "https://dastaminophen.com/"
languageCode: "fa-ir"
title: "داستامینوفن"
theme: "DastaminophenBloggeTheme"
favicon: images/favicon.jpg
paginate: 6
summarylength: 10

menu:
  main:
    [
      { name: "حمایت", url: "/mainpage/donate/", weight: 1 },
      { name: "ارتباط با ما", url: "/contactus", weight: 2 },
      { name: "درباره ما", url: "/aboutus", weight: 3 }
    ]

params:
  summarylength: 80
  logo: "images/logo.jpg"
  author: "ایمان نجیمی"
  authorThumb: "images/author.png"
  instaUsername: "dastaminophen"
  telegramUsername: "dastaminophen"
  twitterUsername: "dastaminophen"
  linkedinUsername: "dastaminophen"
  blogTitle: "داستامینوفن"
  blogSubTitle: "پادکستی برای دوستداران قصّه"
  trendingBlogIcon: "images/blog/icon.svg"
  mainSections: ["mainpage", "shabgheseh", "shahnameh", "magazine"]
  
  podcastlinks:
    [
      {
        name: "کست باکس",
        icon: "/images/apps/castbox.svg",
        link: "https://castbox.fm/channel/id3634536"
      },
      {
        name: "گوگل",
        icon: "/images/apps/google.svg",
        link: "https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5hY2FzdC5jb20vcHVibGljL3Nob3dzLzYyNGFmZDk4ZjNjM2NmMDAxMzRjYzI4YQ"
      },
      {
        name: "اپل",
        icon: "/images/apps/apple.svg",
        link: "https://podcasts.apple.com/us/podcast/dastaminophen-پادکست-فارسی-داستامینوفن/id1545803646"
      },
      {
        name: "اسپاتیفای",
        icon: "/images/apps/spotify.svg",
        link: "https://open.spotify.com/show/6YkPjlh0hAbNIXWY6xhiQR"
      }
    ]


taxonomies:
  type: "types"


